echo Starting installation of Boredem. This could take a while...
echo Creating Boredem directory...
mkdir ~/Boredem
echo Installing 'Discord.JS'...
npm install discord.js
echo Installing 'Colors'...
npm install colors
echo Cloning Boredem GitHub...
git clone https://github.com/boredemdiscord/boredem-js
echo Installation complete! Proceeding to configuration...
sleep 5
nano conf.json
