@echo off
echo Starting installation of Boredem. This could take a while...
cd ~
echo Cloning Boredem GitHub...
git clone https://github.com/boredemdiscord/boredem-js
cd boredem-js
echo Installing 'Discord.js'...
npm install discord.js
echo Installing 'Colors'...
npm install colors
echo Installation complete! Proceeding to configuration...
sleep 5
nano conf.json
